# Generated by Django 3.2.6 on 2023-01-31 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lv', models.IntegerField(default=1)),
                ('next_lv', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=200)),
                ('max_sp', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=200)),
                ('current_sp', models.IntegerField(default=100)),
                ('power', models.IntegerField(default=10)),
                ('resistance', models.IntegerField(default=10)),
                ('agility', models.IntegerField(default=1)),
                ('is_ko', models.BooleanField(default=False)),
                ('is_logged', models.BooleanField(default=False)),
                ('last_activity', models.DateField(null=True)),
                ('position_x', models.IntegerField(default=48)),
                ('position_y', models.IntegerField(default=48)),
                ('area_location', models.CharField(default='citadel', max_length=25)),
                ('items', models.BinaryField(null=True)),
                ('equipment', models.BinaryField(null=True)),
                ('skills', models.BinaryField()),
                ('quests', models.BinaryField(null=True)),
                ('class_type', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
