# Generated by Django 3.2.6 on 2023-02-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='items',
            field=models.BinaryField(default=b'{}'),
        ),
    ]
