# Generated by Django 3.2.6 on 2023-01-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='aim',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='effects',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_activity',
            field=models.DateTimeField(null=True),
        ),
    ]
