# Generated by Django 3.2.6 on 2023-02-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0002_alter_character_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
