# Generated by Django 3.2.6 on 2023-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0003_character_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='wallet',
            field=models.BigIntegerField(default=0),
        ),
    ]
