# Generated by Django 3.2.6 on 2023-02-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0004_alter_character_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=0)),
                ('items', models.BinaryField(default=b'{}')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_app.character')),
            ],
        ),
    ]
