# Generated by Django 3.2.6 on 2023-02-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0005_itemoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpawnedEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=50)),
                ('exp', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=200)),
                ('max_sp', models.IntegerField(default=99999)),
                ('current_hp', models.IntegerField(default=200)),
                ('current_sp', models.IntegerField(default=99999)),
                ('power', models.IntegerField(default=10)),
                ('resistance', models.IntegerField(default=10)),
                ('agility', models.IntegerField(default=1)),
                ('is_ko', models.BooleanField(default=False)),
                ('position_x', models.IntegerField(default=48)),
                ('position_y', models.IntegerField(default=48)),
                ('area_location', models.CharField(max_length=25)),
                ('aim', models.IntegerField(default=100)),
                ('skills', models.BinaryField()),
                ('class_type', models.CharField(default='enemy', max_length=25)),
                ('effects', models.BinaryField(null=True)),
                ('drops', models.BinaryField(null=True)),
            ],
        ),
    ]
