# Generated by Django 3.2.6 on 2023-02-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0007_alter_character_area_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ep',
            field=models.IntegerField(default=0),
        ),
    ]
