# Generated by Django 3.2.6 on 2023-02-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0008_character_ep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='area_location',
            field=models.CharField(default='citadel_central_area', max_length=55),
        ),
        migrations.AlterField(
            model_name='spawnedenemy',
            name='area_location',
            field=models.CharField(max_length=55),
        ),
    ]
