# Generated by Django 3.2.6 on 2023-02-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0009_auto_20230212_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='respawn_spot',
            field=models.CharField(default='citadel_central_area', max_length=55),
        ),
    ]
