# Generated by Django 3.2.6 on 2023-02-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0010_character_respawn_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='position_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='position_y',
            field=models.IntegerField(default=20),
        ),
    ]
