# Generated by Django 3.2.6 on 2023-03-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0011_auto_20230227_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='equipped_skill',
            field=models.IntegerField(null=True),
        ),
    ]
