# Generated by Django 3.2.6 on 2023-03-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0012_character_equipped_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='equipped_item',
            field=models.IntegerField(null=True),
        ),
    ]
